#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZTMDIR=${ZDOTDIR:-$HOME}/.zprezto/thaomaniac
# Source Prezto.
if [[ -s "$ZTMDIR/init.zsh" ]]; then
  source "$ZTMDIR/init.zsh"
fi

# Customize to your needs...

#----- Load Alias Command -----#
if [[ -s "$ZTMDIR/ztm_alias" ]]; then
  source "$ZTMDIR/ztm_alias"
fi

#----- Load Rewrite Theme -----#
if [[ -s "$ZTMDIR/ztm_customize_prompt" ]]; then
  source "$ZTMDIR/ztm_customize_prompt"
fi

#----- Load Custom Completion -----#
if [[ -s "$ZTMDIR/ztm_completion" ]]; then
  source "$ZTMDIR/ztm_completion"
fi

# remove background color 'ls'
export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"

#remove autocompletion color
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS_xx}

# Fix cursor style to I-Beam
_fix_cursor() {
   echo -ne '\e[5 q'
}
precmd_functions+=(_fix_cursor)

# Disable correct command
unsetopt correct

# # Show execute time
# function preexec() {
#  timer=${timer:-$SECONDS}
# }
# function precmd() {
#  if [ $timer ]; then
#    timer_show=$(($SECONDS - $timer))
#    export RPROMPT="${timer_show}s %{$reset_color%}"
#    #export RPROMPT="${timer_show}s %{$reset_color%}%D{%H:%M:%S}"
#    unset timer
#  fi
# }

## Show timestamp
#RPROMPT='%D{%H:%M:%S}'$RPROMPT

# Print a newline before the prompt
function preexec() {
  action="$1"
}
function precmd() {
    #cur_command=$(history -1 | tr -s " " | cut -d ' ' -f 3-)
    if [[ -n $action && $action != "clear" ]]; then
        echo
        unset action
    fi
    if [ -z "$SHOW_HELLO" ]; then
        SHOW_HELLO=1
        _printHello
    fi
}
function _printHello() {
    echo ' ______ __ __ ___   ____   __  ___ ___    _  __ ____ ___   _____'
    echo '/_  __// // // _ | / __ \ /  |/  // _ |  / |/ //  _// _ | / ___/'
    echo ' / /  / _  // __ |/ /_/ // /|_/ // __ | /    /_/ / / __ |/ /__'
    echo '/_/  /_//_//_/ |_|\____//_/  /_//_/ |_|/_/|_//___//_/ |_|\___/'

    echo "\nHello \033[1mVu Thanh Thao\033[0m - $(date '+%Y-%m-%d %H:%M:%S') - $(lsb_release -sd)\n"
}