#!/usr/bin/env zsh

ZTMDIR=${ZDOTDIR:-$HOME}/.zprezto/thaomaniac
# Source Prezto.
if [[ -s "$ZTMDIR/init.zsh" ]]; then
  source "$ZTMDIR/init.zsh"
fi

# load custom command file
tmCustomFile=(
  'agnoster-theme' # Rewrite Theme
  'alias' # Alias Command
  'magento' # Magento Command
  'docker' # Docker command
  'zshprompt' # Custom Function
)
# for file in $ZTMDIR/custom-functions/*; do
for file in $tmCustomFile; do
  file=$ZTMDIR/custom-functions/$file
  if [[ -f $file ]]; then
    source $file
  fi
done
# load local file (not in git)
for file in $ZTMDIR/local/*; do
  if [[ -f $file ]]; then
    source $file
  fi
done

#----- load bg notify -----#
if [[ -s "$ZTMDIR/plugins/zsh-background-notify/bgnotify.plugin.zsh" ]]; then
  source "$ZTMDIR/plugins/zsh-background-notify/bgnotify.plugin.zsh"
fi

# remove background color 'ls'
export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"

#remove autocompletion color
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS_xx}

# Disable correct command
unsetopt correct

# Disable confirm a rm *
# setopt rmstarsilent

# Fix cursor style to I-Beam
#_fix_cursor() {
#   echo -ne '\e[5 q'
#}
#precmd_functions+=(_fix_cursor)

# use a 256 colour terminal
export TERM=xterm-256color
