#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZTMDIR=${ZDOTDIR:-$HOME}/.zprezto/thaomaniac
# Source Prezto.
if [[ -s "$ZTMDIR/init.zsh" ]]; then
  source "$ZTMDIR/init.zsh"
fi

# Customize to your needs...
# load custom command file
for file in $ZTMDIR/custom-functions/*; do
  if [[ -f $file ]]; then
    source $file
  fi
done
# load local file (not in git)
for file in $ZTMDIR/local/*; do
  if [[ -f $file ]]; then
    source $file
  fi
done

#----- load bg notify -----#
if [[ -s "$ZTMDIR/plugins/zsh-background-notify/bgnotify.plugin.zsh" ]]; then
  source "$ZTMDIR/plugins/zsh-background-notify/bgnotify.plugin.zsh"
fi

# remove background color 'ls'
export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"

#remove autocompletion color
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS_xx}

# Fix cursor style to I-Beam
_fix_cursor() {
   echo -ne '\e[5 q'
}
precmd_functions+=(_fix_cursor)

# Disable correct command
unsetopt correct
