#!/usr/bin/env zsh

###----------Agnoster theme - Rewrite Prompt components----------###

# End the prompt, closing any open segments
prompt_end() {
  if [[ -n $CURRENT_BG ]]; then
    if [[ $PWD != "$HOME" ]]; then
      print -n "%{%k%F{green}%}\n❯%B_%b"
    else
      print -n "%{%k%F{green}%}❯%B_%b"
    fi
  else
    print -n "%{%k%}"
  fi
  print -n "%{%f%}"
  CURRENT_BG=''
}

# Dir: current working directory
prompt_dir() {
  if [[ $PWD != "$HOME" ]]; then
    prompt_segment default default '%~'
  fi
  #prompt_segment default default ' %4c'
}

# Context: user@hostname (who am I and where am I)
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    if [[ $PWD != "$HOME" ]]; then
      START_ICON=''
      load_dir_icon
      prompt_segment default green "%(!.%{%F{white}%}.)$START_ICON "
    fi
  fi
}

# Icon for begin the prompt with Nerd Font
load_dir_icon() {
  if [[ $PWD/ == /home/* ]]; then
    START_ICON="\uf015" #
    return 1
  elif [[ -s "$PWD/bin/magento" ]]; then
    START_ICON="\ue740" #
    return 1
  elif [[ -s "$PWD/spark" && -d "$PWD/vendor/codeigniter4" ]]; then
    START_ICON="\ue780" #
    return 1
  else
    START_ICON="\uf31b" #
    #START_ICON="\uf07c" #
  fi
  if [[ ! -w $PWD ]]; then
    local -i w=$?
    START_ICON="\uf023" #
  fi
}
#➜

# Git: branch/detached head, dirty status
prompt_git() {
  local color ref
  is_dirty() {
    test -n "$(git status --porcelain --ignore-submodules)"
  }
  ref="$vcs_info_msg_0_"
  if [[ -n "$ref" ]]; then
    if is_dirty; then
      color=yellow
      ref="${ref} $PLUSMINUS"

      countAll="$(git status -s -u | wc -l)"
      [[ $countAll -ne 0 ]] && ref="$ref$countAll%f"
      # countTracked="$(git status -s -uno | wc -l)"
      # countAdded="$(git diff --cached --numstat | wc -l)"
      # [[ $countAdded -ne 0 ]] && ref="$ref $countAdded"
    else
      color=green
      ref="%B${ref}%b \U2714"
    fi
    if [[ "${ref/.../}" == "$ref" ]]; then
      ref="$BRANCH $ref"
    else
      ref="$DETACHED ${ref/.../}"
    fi
    prompt_segment default $color
    print -n " $ref"
  fi
}

# Status:
# - was there an error
# - am I root
# - are there background jobs?
prompt_status() {
  local symbols
  symbols=()
  if [[ $RETVAL -eq 130 ]]; then
    symbols+="%{%F{default}%}$CROSS"
  elif [[ $RETVAL -ne 0 ]]; then
    symbols+="%{%F{red}%}$CROSS $CROSS $CROSS"
  fi
  [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}$LIGHTNING"
  [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}$GEAR"

  [[ -n "$symbols" ]] && prompt_segment default default "$symbols\n"
}
