#!/usr/bin/env zsh

alias update='sudo apt-get update'
alias autoremove='sudo apt-get autoremove'
alias autoclean='sudo apt-get autoclean'

#alias colorls command
if type "colorls" >/dev/null; then
  alias ls='colorls --indicator-style=none'
fi

# Switch php version
switch-php() {
  if [ -z "$1" ]; then
    sudo update-alternatives --config php
  else
    if [[ $1 =~ ^[0-9]\.[0-9]$ ]]; then #x.y # $1 == ?.?
      sudo update-alternatives --set php /usr/bin/php"$1"
    elif [[ $1 =~ ^[0-9]\[0-9]$ ]]; then #xy
      # shellcheck disable=SC2001
      sudo update-alternatives --set php /usr/bin/php"$(sed 's/./&./' <<<"$1")"
    elif [[ $1 =~ ^php\[0-9]\.[0-9]$ ]]; then #phpx.y
      sudo update-alternatives --set php /usr/bin/"$1"
    else
      sudo update-alternatives --set php /usr/bin/php"$1"
    fi
  fi
}
_list_all_php_ver() {
  # shellcheck disable=SC2046
  compadd $(update-alternatives --list php | sed "s/.*php//g") #sed 's/^.*php/php/
}
compdef _list_all_php_ver switch-php

# Restart service
restart-service() {
  sudo service "$1" restart
}
compdef _service restart-service
##----------GIT command----------##

# git commit with branch name as prefix
# commit message must be enclosed in quotation marks
commit() {
  # local branch=$(git-branch-current 2> /dev/null);
  # shellcheck disable=SC2154
  local branch=$vcs_info_msg_0_
  if [ -z "$branch" ]; then
    echo "\e[1;31mUnknown branch name\e[0m"
    return 1
  fi
  if [[ $# != 1 ]]; then
    echo "\e[1;31mTypeScript Error:\e[0m Expected 1 arguments, but got $#!"
    return 1
  else
    # shellcheck disable=SC2155
    local msg=$(echo "$1" | cut -c1 | command tr a-z A-Z)$(echo "$1" | cut -c2-)
    git commit -m "$branch: $msg"
  fi
}

# git push --set-upstream origin <branch>
pushSetUpstream() {
  local branch=$vcs_info_msg_0_
  if [ -z "$branch" ]; then
    echo "\e[1;31mUnknown branch name\e[0m"
    return 1
  else
    git push --set-upstream origin "$branch"
  fi
}

##----------END git command----------##

##----------CodeIgniter command----------##

alias ci='php spark'

##----------END CodeIgniter command----------##

# Reset 30 days trial phpstorm
alias phpstorm_reset='rm -f ~/.config/JetBrains/PhpStorm*/options/other.xml;rm -rf ~/.config/JetBrains/PhpStorm*/eval;rm -rf ~/.java/.userPrefs'
