#!/usr/bin/env zsh
##----------Magento command----------##

# check is current directory is magento
ism2dir() {
  if [ -f "$PWD/bin/magento" ]; then
    return 0 #true
  fi
  return 1 # false
}
_print_msg_not_m2_dir() {
  echo "Current directory is not the magento folder"
}

# composer with magento
composer() {
  local composerPath=/usr/local/bin/composer
  if ism2dir; then
    eval "$(_phpVer)" $composerPath "$@"
  else
    $composerPath "$@"
  fi
}

#---Alias with Nginx multiple php
m2() {
  # shellcheck disable=SC2046
  eval $(_phpVer) bin/magento "$@"
}
alias cc='eval $(_phpVer) bin/magento cache:clean'
alias cf='eval $(_phpVer) bin/magento cache:flush'
alias sdc='eval $(_phpVer) bin/magento setup:di:compile'
alias ssd='eval $(_phpVer) bin/magento setup:static-content:deploy'
alias seup='eval $(_phpVer) bin/magento setup:upgrade'
alias sup='eval $(_phpVer) bin/magento setup:upgrade'

# deploy production mode
m2-deploy-prod() {
  phpVersion=$(_phpVer)
  echo '----- deploying production mode -----'
  $phpVersion bin/magento maintenance:enable &&
    $phpVersion bin/magento setup:upgrade &&
    $phpVersion bin/magento deploy:mode:set production -s &&
    $phpVersion bin/magento setup:di:compile &&
    $phpVersion bin/magento setup:static-content:deploy en_US vi_VN -f -j 4 &&
    $phpVersion bin/magento cache:flush &&
    $phpVersion bin/magento maintenance:disable
}

_phpVer() {
  _m2phpVerFile
}
# get version from saved file
_m2phpVerFile() {
  ! ism2dir && echo 'php' && return

  local fileDir="$ZTMDIR/local/magento/"
  local file="$fileDir/php_version"
  local phpVer
  local line=0

  if [ ! -f "$file" ]; then
    mkdir "$fileDir" && touch "$file"
  else
    # shellcheck disable=SC2162
    while IFS=':' read -A args; do
      ((line++))
      if [[ ${args[1]} == "$PWD" ]]; then
        phpVer="${args[2]}"
        break
      fi
    done <"$file"
  fi

  if [ -z "$phpVer" ]; then
    phpVer=$(_m2checkPhpVer)
    echo "$PWD:$phpVer" >>"$file"
  elif [[ -n $1 && $1 == "update" ]]; then
    phpVer=$(_m2checkPhpVer)
    sed -i "$line s|.*|$PWD:$phpVer|" "$file"
    #sed -i "$line c$PWD:$phpVer" $file
  fi
  echo "$phpVer"
}

m2-gen-php-version() {
  if ism2dir; then
    _m2phpVerFile 'update'
  else
    _print_msg_not_m2_dir
    return 1
  fi
}

_m2checkPhpVer() {
  if ! ism2dir; then
    echo "php"
    return
  fi

  for ver in '' 7.4 7.3 8.1; do
    magentoVer=$(php$ver bin/magento -V | tail -n 1 | awk '{print $NF}' | cut -c1-5) >/dev/null 2>&1
    if [[ $magentoVer =~ ^[0-9]+(\.[0-9]+){2,3}$ ]]; then
      break
    fi
  done

  case $magentoVer in
  '2.3.5' | '2.3.6')
    echo 'php7.3'
    ;;
  '2.3.7' | '2.4.0' | '2.4.1' | '2.4.2' | '2.4.3')
    echo 'php7.4'
    ;;
  *)
    echo 'php8.1'
    ;;
  esac
}

##----------Completion----------##

_loadMagentoFilePathCompletion() {
  rootDir="$ZTMDIR/local/magento/completion"
  fileDir="$rootDir$PWD"
  filePath="$fileDir/m2_cli"
  n98filePath="$fileDir/n98_cli"
}
m2-gen-cli-completion() {
  if ism2dir; then
    _loadMagentoFilePathCompletion
    rm -f "$filePath" && #nocorrect rm -i
      mkdir "$fileDir" && #nocorrect /bin/mkdir -p
      m2 --raw --no-ansi list | sed "s/[[:space:]].*//g" >"$filePath"
  else
    _print_msg_not_m2_dir
    return 1
  fi
}

# magento
_magento_list_command() {
  #  m2 --raw --no-ansi list | sed "s/[[:space:]].*//g"
  _loadMagentoFilePathCompletion
  if [[ -s $filePath ]]; then
    cat "$filePath"
  fi
}
_magento_autocomplete() {
  if ism2dir; then
    echo 1
    # shellcheck disable=SC2154
    for word in "${words[@]:1}"; do
      if [[ $word != -* ]]; then
        curW=$word
        break
      fi
    done
    case "$curW" in
    module:enable)
      # shellcheck disable=SC2046
      compadd $(m2 module:status --disabled)
      return
      ;;
    module:disable)
      # shellcheck disable=SC2046
      compadd $(m2 module:status --enabled)
      return
      ;;
    indexer:reindex)
      # shellcheck disable=SC2046
      compadd $(m2 indexer:info | sed "s/[[:space:]].*//g")
      return
      ;;
    deploy:mode:set)
      compadd developer production default
      return
      ;;
    admin:user:create)
      compadd - --admin-user --admin-password --admin-email --admin-firstname --admin-lastname --magento-init-params
      return
      ;;
    esac
    # shellcheck disable=SC2046
    compadd $(_magento_list_command)
  fi
}
compdef _magento_autocomplete m2 bin/magento

# netz98 magerun CLI tools for Magento 2 https://github.com/netz98/n98-magerun2
n98() {
  # shellcheck disable=SC2046
  eval $(_phpVer) /usr/local/bin/n98-magerun2.phar "$@"
}

n98-m2-gen-cli-completion() {
  _loadMagentoFilePathCompletion
  if ism2dir; then
    rm -f "$n98filePath" && #nocorrect rm -i
      mkdir "$fileDir" && #nocorrect /bin/mkdir -p
      n98 --raw --no-ansi list | sed "s/[[:space:]].*//g;/^$/d" >"$n98filePath"
  else
    rm -f "$rootDir/n98_cli" && #nocorrect rm -i
      mkdir "$rootDir" && #nocorrect /bin/mkdir -p
      n98 --raw --no-ansi list | sed "s/[[:space:]].*//g;/^$/d" >"$rootDir/n98_cli"
    echo -ne "\033[1mNotice:\033[0m " && _print_msg_not_m2_dir
  fi
}

#compdef n98-magerun2.phar
_n98_magerun2_list_command() {
  _loadMagentoFilePathCompletion
  if ism2dir; then
    if [[ -s "$n98filePath" ]]; then
      cat "$n98filePath"
    fi
  else
    if [[ -s "$rootDir/n98_cli" ]]; then
      cat "$rootDir/n98_cli"
    fi
  fi
}

_n98_magerun2_autocomplete() {
  # shellcheck disable=SC2046
  compadd $(_n98_magerun2_list_command)
}
compdef _n98_magerun2_autocomplete n98 n98-magerun2.phar
##----------END Completion----------##
