#!/usr/bin/env zsh

# alias restart service
compdef _service restart-service

# magento
_magento_list_command() {
  #  m2 --raw --no-ansi list | sed "s/[[:space:]].*//g"
  cat "$ZTMDIR"/completion/magento_cli
}
_magento_autocomplete() {
  if [[ -s "$PWD/bin/magento" ]]; then
    # shellcheck disable=SC2046
    compadd $(_magento_list_command)
  fi
}
compdef _magento_autocomplete m2 bin/magento

#compdef n98-magerun2.phar
_n98_magerun2_get_command_list() {
  n98-magerun2.phar --raw --no-ansi list | sed "s/[[:space:]].*//g"
}

_n98_magerun2() {
  # shellcheck disable=SC2046
  compadd $(_n98_magerun2_get_command_list)
}

compdef _n98_magerun2 n98-magerun2.phar
