#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
# Customizer:
#   Vu Thanh Thao <thaomaniac@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/thaomaniac/custom/initialize.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/thaomaniac/custom/initialize.zsh"
elif [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
