#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
# Customizer:
#   Vu Thanh Thao <thaomaniac@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/thaomaniac/custom/initialize" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/thaomaniac/custom/initialize"
fi
