#!/usr/bin/env zsh
#check the current directory is docker or is in the directory containing docker
isDockerComposeDir() {
  if [[ -n $1 && $1 == "parent" ]]; then
    local current_directory
    current_directory=$(pwd)
    while [[ "$current_directory" != "/" ]]; do
      if [ -f "$current_directory/docker-compose.yml" ]; then
        return 0 #true
      fi
      current_directory=$(dirname "$current_directory")
    done
    return 1 # false
  else
    if [ -f "$PWD/docker-compose.yml" ]; then
      return 0 #true
    fi
    return 1 # false
  fi
}

isDockerDir(){
  isDockerComposeDir 'parent'
}

unalias dkc >/dev/null 2>&1
function dkc() {
  docker compose "$@"
}

_docker_compose_completion() {
compadd  tes1 test2 test3
}
compdef _docker_compose_completion dkc

##---Magento command with docker
_m2-docker() {
  docker compose exec -T php bash -c "bin/magento $*"
}
_m2-normal() {
  eval "$(_phpVer)" bin/magento "$@"
}

m2() {
  if isDockerDir; then
    _m2-docker "$@"
  else
    _m2-normal "$@"
  fi
}
