#!/usr/bin/env zsh

#check the current directory is docker or is in the directory containing docker
# 0 true; 1 false
# shellcheck disable=SC2120
isDockerDir() {
  if [[ -z $IS_DOCKER_DIR || $1 == "-f" ]]; then
    IS_DOCKER_DIR=1
    local current_directory
    current_directory=$(pwd)
    while [[ "$current_directory" != "/" ]]; do
      if [ -f "$current_directory/docker-compose.yml" ]; then
        DOCKER_ROOT=$current_directory
        IS_DOCKER_DIR=0
      fi
      current_directory=$(dirname "$current_directory")
    done
  fi

  return "$IS_DOCKER_DIR"
}

_check_docker_dir() {
  unset IS_DOCKER_DIR
  isDockerDir
}
add-zsh-hook chpwd _check_docker_dir

unalias dkc >/dev/null 2>&1
function dkc() {
  docker compose "$@"
}

dkc-script() {
  if isDockerDir; then
    scriptCommand=$1
    shift
    "$DOCKER_ROOT/scripts/$scriptCommand" "$@"
  else
    echo 'Current directory is not a docker environment, abort action!'
    return 1
  fi
}

# Define completion function for dkc-script
_dkc-script_completion() {
  if ! isDockerDir; then
    return
  fi
  local commands_xdebug
  commands_xdebug=(
    'enable:Enable Xdebug'
    'on:Enable Xdebug'
    'disable:Disable Xdebug'
    'off:Disable Xdebug'
    'status:Status Xdebug'
  )

  local commands_database
  commands_database=(
    'create:Create database'
    'drop:Drop database'
    'import:Import database'
    'export:Export database'
  )

  if [[ ${words[2]} == "xdebug" ]]; then
    if [[ ${#words[@]} -eq 3 || ${words[3]} == php* ]]; then
      _describe 'xdebug command' commands_xdebug
    fi
  elif [[ ${words[2]} == "database" ]]; then
    if [[ ${#words[@]} -eq 3 ]]; then
      _describe 'database command' commands_database
    fi
  else
    local commands
    commands=(
      'xdebug:Xdebug command description'
      'database:Database command description'
    )
    _describe 'command' commands
  fi
}
compdef _dkc-script_completion dkc-script

#_docker_compose_completion() {
#compadd  tes1 test2 test3
#}
#compdef _docker_compose_completion dkc

##---Magento command with docker
_m2DockerPhpVerFile() {
  local file="$DOCKER_ROOT/.php-map"
  local phpVer='php'

  if [ -f "$file" ]; then
    while IFS=: read -r folder php_version; do
      if [[ "$PWD" == *"/$folder" ]]; then
        phpVer=$php_version
        break
      fi
    done <"$file"
  fi
  echo "$phpVer"
}

_isMultiDocker() {
  if [ -f "$DOCKER_ROOT/.php-map" ]; then
    return 0 #true
  fi
  return 1 # false
}

_m2-docker() {
  if _isMultiDocker; then
    ! ism2dir && _print_msg_not_m2_dir && return 1
    local phpService=$(_m2DockerPhpVerFile)
    local lastDir=${PWD##*/}
    local workingDir=$(docker inspect --format='{{.Config.WorkingDir}}' $(docker compose ps -q $phpService))
    local working_dir="$workingDir/$lastDir"
    docker compose exec -T "$phpService" bash -c "cd $working_dir && bin/magento $*"
  else
    local phpService='php'
    local workingDir=$(docker inspect --format='{{.Config.WorkingDir}}' $(docker compose ps -q $phpService))
    local working_dir="$workingDir"
    docker compose exec -T "$phpService" bash -c "cd $working_dir && bin/magento $*"
  fi
}

_m2-normal() {
  eval "$(_phpVer)" bin/magento "$@"
}

m2() {
  if isDockerDir; then
    _m2-docker "$@"
  else
    _m2-normal "$@"
  fi
}
