#!/usr/bin/env zsh

function _poweredBy() {
  echo 'IF9fX19fX19fIF9fX19fICBfX19fICBfXyAgX19fX19fICAgXyAgX19fX19fX19fICBfX19fXwov' | base64 -d
  echo 'XyAgX18vIC8vIC8gXyB8LyBfXyBcLyAgfC8gIC8gXyB8IC8gfC8gLyAgXy8gXyB8LyBfX18vCiAv' | base64 -d
  echo 'IC8gLyBfICAvIF9fIC8gL18vIC8gL3xfLyAvIF9fIHwvICAgIC8vIC8vIF9fIC8gL19fICAKL18v' | base64 -d
  echo 'IC9fLy9fL18vIHxfXF9fX18vXy8gIC9fL18vIHxfL18vfF8vX19fL18vIHxfXF9fXy8gIAo=' | base64 -d
  # http://patorjk.com/software/taag/#p=display&h=2&f=Small%20Slant&t=THAOMANIAC
}
function _greeting-tm() {
  _poweredBy
  # shellcheck disable=SC2028
  echo "\n\033[1;5m$USER\033[0m - $(date '+%Y-%m-%d %H:%M:%S') \e[5m-\e[0m $(lsb_release -sd)\n"
}
_greeting-tm

_set-window-title-tm() {
  local title
  if [[ $PWD == /var/www/* ]]; then
    # parts=(${(@s:/:)PWD});title="${parts[3]}"
    local lastPwd=${PWD#*/var/www/}
    title=${lastPwd%%/*}
  else
    title="${PWD/#$HOME/~}"
  fi
  printf '\e]2;%s\a' "$title"
}
_set-window-title-tm
add-zsh-hook chpwd _set-window-title-tm

# Elapsed and execution time display for commands
# https://gist.github.com/knadh/123bca5cfdae8645db750bfb49cb44b0
function elapsed_preexec() {
  if [[ "$SHOW_ELAPSED" == 1 ]]; then
    epLastCmd="$1"
    [[ -n $epLastCmd && $epLastCmd != "clear" && $epLastCmd != "reset" ]] && \
    elapsedTimer=$(date +%s%3N)
  fi
}
elapsed_precmd() {
  if [[ "$SHOW_ELAPSED" && "$elapsedTimer" ]]; then
    local -r now=$(date +%s%3N)
    local -rF d_ms=$(($now - $elapsedTimer))
    local -rF d_s=$((d_ms / 1000))
    local -rF ms=$((d_ms % 1000))
    local -rF s=$((d_s % 60))
    local -ri m=$(((d_s / 60) % 60))
    local -ri h=$((d_s / 3600))
    if ((h > 0)); then
      printf -v elapsed '%ih%im%is' ${h} ${m} ${s}
    elif ((m > 0)); then
      printf -v elapsed '%im%is' ${m} ${s}
    elif ((s >= 1)); then
      printf -v elapsed '%.2fs' ${s}
    else
      printf -v elapsed '%ims' ${ms}
    fi
    RPROMPT="${elapsed}"
    if [ "$SHOW_TIMESTAMP" ]; then
      RPROMPT+="|%D{%H:%M:%S}"
    fi
    unset elapsedTimer
    unset elapsed
  elif [ "$SHOW_TIMESTAMP" ]; then
    RPROMPT="%D{%H:%M:%S}"
  else
    unset RPROMPT
  fi
}
showTimePrompt() {
  unset SHOW_TIMESTAMP
  unset SHOW_ELAPSED
  if [[ -z $1 ]]; then
    SHOW_TIMESTAMP=1;
    SHOW_ELAPSED=1;
  else
    if [[ $1 == 1 ]]; then
     SHOW_ELAPSED=1;
    fi
    if [[ $2 == 1 ]]; then
      SHOW_TIMESTAMP=1;
    fi
  fi
}
add-zsh-hook preexec elapsed_preexec
add-zsh-hook precmd elapsed_precmd
# END Elapsed and execution time

# override bgnotify_formatted
function bgnotify_formatted() { ## args: (exit_status, command, elapsed_seconds)
  elapsed="$(($3 % 60))s"
  (($3 >= 60)) && elapsed="$((($3 % 3600) / 60))m $elapsed"
  (($3 >= 3600)) && elapsed="$(($3 / 3600))h $elapsed"
  [ $1 -eq 0 ] && notify-send -i org.gnome.Terminal "Success ($elapsed)✔" "$2" || notify-send -i org.gnome.Terminal "FAIL ($elapsed)✘" "$2"
}
