#!/usr/bin/env zsh
#check the current directory is docker or is in the directory containing docker
isDockerComposeDir() {
  if [[ -n $1 && $1 == "parent" ]]; then
    local current_directory
    current_directory=$(pwd)
    while [[ "$current_directory" != "/" ]]; do
      if [ -f "$current_directory/docker-compose.yml" ]; then
        return 0 #true
      fi
      current_directory=$(dirname "$current_directory")
    done
    return 1 # false
  else
    if [ -f "$PWD/docker-compose.yml" ]; then
      return 0 #true
    fi
    return 1 # false
  fi
}

isDockerDir(){
  isDockerComposeDir 'parent'
}

alias dk=docker
function dkc() {
  docker compose "$@"
}

_docker_compose_completion() {
  if isDockerDir; then
#    # get first command
#    for word in "${words[@]:1}"; do
#      if [[ $word != -* ]]; then #ignore words starting with a dash -
#        curW=$word
#        break
#      fi
#    done

    # get last command
    for (( i=${#words[@]}-1; i>0; i-- )); do
      word="${words[$i]}"
      if [[ -n $word && $word != -* ]]; then
        curW=$word
        break
      fi
    done
    # local wordsCount=$(($(IFS=' '; set -- $words; echo $#) - 1));
    case "$curW" in
      exec )
      docker compose ps --format "{{.Service}} {{.ID}}" | while read -r line; do
        service_name=${line%% *}
        container_id=${line#* }
        compadd -V "$line" "$service_name"
      done
      return
      ;;
    esac
      # shellcheck disable=SC2046
      return
  fi
}
compdef _docker_compose_completion dkc

##---Magento command with docker
_m2-docker() {
  docker compose exec -T php bash -c "bin/magento $*"
}
_m2-normal() {
  eval "$(_phpVer)" bin/magento "$@"
}

m2() {
  if isDockerDir; then
    _m2-docker "$@"
  else
    _m2-normal "$@"
  fi
}
